export const fieldsData = {
    "affidavit": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Myear", "name": "myear", "type": "number" },
        { "label": "OPNO", "name": "OPNO", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" }
    ],
    "amendament": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Myear", "name": "myear", "type": "number" },
        { "label": "OPNO", "name": "OPNO", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" }
    ],
    "antiBail": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Myear", "name": "myear", "type": "number" },
        { "label": "OPNO", "name": "OPNO", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" }
    ],
    "appealSuit": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Myear", "name": "myear", "type": "number" },
        { "label": "OPNO", "name": "OPNO", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" }
    ],
    "bail": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "OP / Crime Number", "name": "OPNO", "type": "text" },
        { "label": "OP / Crime Date", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court Name", "name": "lowercourt", "type": "text" },
        { "label": "Counsel Address", "name": "counsel_address", "type": "text" },
        { "label": "Date of Offence", "name": "date_offence", "type": "date" },
        { "label": "Place of Offence", "name": "place_offence", "type": "text" },
        { "label": "Offence Under Section", "name": "offence_section", "type": "text" },
        { "label": "Date of Remand", "name": "date_remand", "type": "date" },
        { "label": "Previous Crl.M.P. Number", "name": "prev_crlmp_no", "type": "text" },
        { "label": "Previous Court Name", "name": "prev_court", "type": "text" },
        { "label": "Previous Order Date", "name": "prev_order_date", "type": "date" },
        { "label": "Date of Arrest", "name": "date_arrest", "type": "date" },
        { "label": "Name of Jail", "name": "jail_name", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "Verification By", "name": "verification", "type": "text" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Bar Council Enrollment No.", "name": "R25", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "textarea" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "textarea" }
    ],
    "ca": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "Order / OP Date", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court Name", "name": "lowercourt", "type": "text" },
        { "label": "Counsel Address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Date of Offence", "name": "date_offence", "type": "date" },
        { "label": "Place of Offence", "name": "place_offence", "type": "text" },
        { "label": "Offence Under Section", "name": "offence_section", "type": "text" },
        { "label": "Date of Remand", "name": "date_remand", "type": "date" },
        { "label": "Date of Arrest", "name": "date_arrest", "type": "date" },
        { "label": "Name of Jail", "name": "name_jail", "type": "text" },
        { "label": "Verification / Person Interested", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Bar Council Enrollment No.", "name": "R25", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" }
    ],
    "caveat": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Caveat Petition Number", "name": "caveat_no", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "W.P. Number", "name": "wp_no", "type": "text" },
        { "label": "Lower Court / OP Number", "name": "OPNO", "type": "text" },
        { "label": "Lower Court Name", "name": "lowercourt", "type": "text" },
        { "label": "Verification / Deponent Name", "name": "verification", "type": "text" },
        { "label": "Place / Station", "name": "place", "type": "text" },
        { "label": "Counsel Address", "name": "counsel_address", "type": "text" },
        { "label": "Interim Prayer", "name": "interim_prayer", "type": "text" },
        { "label": "Order Date / OP Date", "name": "OPDATE", "type": "date" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "District", "name": "district", "type": "text" }
    ],
    "centralExciseAppeal": [
        { "label": "High Court", "name": "highcourt", "type": "text", "value": "<<highcourt>>" },
        { "label": "C.E.A. No.", "name": "CEA_No", "type": "text", "value": "<<CEA.No.>>" },
        { "label": "Case Year", "name": "myear", "type": "number", "value": "<<myear>>" },
        { "label": "Order in Original No.", "name": "order_in_original_no", "type": "text", "value": "<<Order in Original No.>>" },
        { "label": "Order in Appeal No.", "name": "order_in_appeal_no", "type": "text", "value": "<<Order in Appeal No.>>" },
        { "label": "Final Order No.", "name": "final_order_no", "type": "text", "value": "<<Final Order No.>>" },
        { "label": "Verification / Petitioner Name", "name": "verification", "type": "text", "value": "<<verification>>" },
        { "label": "Place", "name": "place", "type": "text", "value": "<<place>>" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text", "value": "<<MAIN_PRAYER>>" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text", "value": "<<INTERIM_PRAYER>>" },
        { "label": "Filing Date", "name": "fdate", "type": "date", "value": "<<fdate>>" },
        { "label": "District", "name": "district", "type": "text", "value": "<<district>>" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text", "value": "<<counsel_code>>" },
        { "label": "Value of Appeal", "name": "appeal_value", "type": "number", "value": "<<appeal_value>>" },
        { "label": "Court Fee Paid", "name": "court_fee", "type": "number", "value": "<<court_fee>>" },
        { "label": "Stamp Duty Paid", "name": "stamp_duty", "type": "number", "value": "<<stamp_duty>>" },
        { "label": "Batta / Process Fee", "name": "batta_fee", "type": "number", "value": "<<batta_fee>>" },
        { "label": "Lower Court Name", "name": "lowercourt", "type": "text", "value": "<<lowercourt>>" },
        { "label": "Lower Court Case Number", "name": "OPNO", "type": "text", "value": "<<OPNO>>" },
        { "label": "Lower Court Order Date", "name": "OPDATE", "type": "date", "value": "<<OPDATE>>" }
    ],
    "cma": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "C.M.A. No.", "name": "CMA_No", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Order No.", "name": "OPNO", "type": "text" },
        { "label": "Order Date", "name": "OPDATE", "type": "date" },
        { "label": "Petitioner Name/Address", "name": "petitioner_name", "type": "text" },
        { "label": "Respondent Name/Address", "name": "respondent_name", "type": "text" },
        { "label": "Counsel Name/Address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification / Deponent", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Petitioner Age", "name": "R23", "type": "number" },
        { "label": "Respondent Age", "name": "R24", "type": "number" },
        { "label": "Bar Council Enrollment No.", "name": "R25", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Court Fee", "name": "court_fee", "type": "number" },
        { "label": "Stamp Duty Paid", "name": "stamp_duty", "type": "number" },
        { "label": "Batta / Process Fee", "name": "batta_fee", "type": "number" },
        { "label": "IA / Interlocutory Applications", "name": "IA_details", "type": "text" },
        { "label": "Running Index", "name": "running_index", "type": "array" }
    ],
    "civilRevisionPetition": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Order No.", "name": "OPNO", "type": "text" },
        { "label": "Order Date", "name": "OPDATE", "type": "date" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "Counsel Name/Address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification / Deponent", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Bar Council Enrollment No.", "name": "R25", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Court Fee", "name": "court_fee", "type": "number" },
        { "label": "Stamp Duty Paid", "name": "stamp_duty", "type": "number" },
        { "label": "Batta / Process Fee", "name": "batta_fee", "type": "number" },
        { "label": "IA / Interlocutory Applications", "name": "IA_details", "type": "text" },
        { "label": "Running Index", "name": "running_index", "type": "array" },
        { "label": "Filing Numbers", "name": "filing_numbers", "type": "object" },
        { "label": "Full Cause Title", "name": "full_cause_title", "type": "text" },
        { "label": "IA(s) Prayer", "name": "IA_PRAYER", "type": "text" }
    ],
    "companyPetition": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Company Petition No.", "name": "CP_NO", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "Counsel Name/Address", "name": "counsel_address", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Verification / Deponent", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Official Liquidator Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Main Petition Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Court Fee Paid", "name": "court_fee", "type": "number" },
        { "label": "Registered Office of Respondent", "name": "registered_office", "type": "text" },
        { "label": "Authorised Share Capital", "name": "auth_share_capital", "type": "text" },
        { "label": "Issued/ Paid-up Capital", "name": "paidup_capital", "type": "text" },
        { "label": "Main Objects of Respondent Company", "name": "main_objects", "type": "array" },
        { "label": "Material Papers / Documents Filed", "name": "material_papers", "type": "text" },
        { "label": "IA / Interlocutory Applications", "name": "IA_details", "type": "text" },
        { "label": "Judge's Summons Details", "name": "judge_summons", "type": "text" },
        { "label": "Running Index / Pages", "name": "running_index", "type": "array" },
        { "label": "Filing Numbers", "name": "filing_numbers", "type": "object" },
        { "label": "Full Cause Title", "name": "full_cause_title", "type": "text" },
        { "label": "IA(s) Prayer", "name": "IA_PRAYER", "type": "text" }
    ],
    "compromiseHc": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "I.A. Number", "name": "ia_no", "type": "text" },
        { "label": "Crl.P. Number", "name": "crlp_no", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Complaint/Order Number", "name": "OPNO", "type": "text" },
        { "label": "Complaint/Order Date", "name": "OPDATE", "type": "date" },
        { "label": "Verification/Deponent", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Running Index", "name": "running_index", "type": "text" }
    ],
    "contemptCase": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "Contempt Case Number", "name": "cc_no", "type": "text" },
        { "label": "Case Year", "name": "myear", "type": "number" },
        { "label": "Order/Case Number", "name": "OPNO", "type": "text" },
        { "label": "Order/Case Date", "name": "OPDATE", "type": "date" },
        { "label": "Lower Court", "name": "lowercourt", "type": "text" },
        { "label": "Verification / Deponent", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Main Prayer", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Running Index", "name": "running_index", "type": "text" }
    ],
    "counter": [
        { "label": "High Court", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "Place", "name": "place", "type": "text" },
        { "label": "Filing Date", "name": "fdate", "type": "date" },
        { "label": "District", "name": "district", "type": "text" },
        { "label": "Counsel Code", "name": "counsel_code", "type": "text" },
        { "label": "Interim Prayer", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "DISTRICT", "name": "DISTRICT", "type": "text" },

    ],
    "criminalAppeal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "criminalRevisionCase": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "criminalRevisionCaseMacma": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "crossObjections": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "debtsRecoveryTribunal": [
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "delayInRepresentation": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "dispense": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "expedite": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "extension": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
    ],
    "familyCourtsAppeal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "forbeing": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
    ],
    "implead": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "incomeTaxAppellateTribunal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "leave": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
    ],
    "lrPetPet": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
    ],
    "lrPreTreps": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
    ],
    "memoForProofOfService": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
    ],
    "transferCriminalPetition": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "transferMiscPetition": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "originalSideAppeal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "pil": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "quash": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
    ],
    "receiveAndTransmit": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "reviewPetition": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
    ],
    "secondAppeal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "stateConsumerRedressalCommission": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "taxAppellateTribunal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "vacate": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
    ],
    "vacateMacma": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
    ],
    "vakalath": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
    ],
    "writIa": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
    ],
    "writAppeal": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ],
    "writPetition": [
        { "label": "highcourt", "name": "highcourt", "type": "text" },
        { "label": "OPNO", "name": "OPNO", "type": "number" },
        { "label": "lowercourt", "name": "lowercourt", "type": "text" },
        { "label": "myear", "name": "myear", "type": "number" },
        { "label": "OPDATE", "name": "OPDATE", "type": "date" },
        { "label": "place", "name": "place", "type": "text" },
        { "label": "fdate", "name": "fdate", "type": "date" },
        { "label": "counsel_code", "name": "counsel_code", "type": "text" },
        { "label": "counsel_address", "name": "counsel_address", "type": "text" },
        { "label": "district", "name": "DISTRICT", "type": "text" },
        { "label": "Verification", "name": "verification", "type": "text" },
        { "label": "INTERIM_PRAYER", "name": "INTERIM_PRAYER", "type": "text" },
        { "label": "R23", "name": "R23", "type": "number" },
        { "label": "R24", "name": "R24", "type": "number" },
        { "label": "R25", "name": "R25", "type": "number" },
        { "label": "MAIN_PRAYER", "name": "MAIN_PRAYER", "type": "text" },
    ]
}