export const initialValues = {
    affidavit: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        place: "",
        fdate: "",
        district: "",
        counsel_address: "",
        counsel_code: "",
        verification: "",
        MAIN_PRAYER: "",
        INTERIM_PRAYER: ""
    },
    amendament: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        place: "",
        fdate: "",
        district: "",
        counsel_address: "Chamber No. 5, Advocate Chambers, Supreme Block, Hyderabad - 500032",
        counsel_code: "HYD-002",
        verification: "Verified at Hyderabad",
        MAIN_PRAYER: "Prayer to allow amendment of the plaint",
        INTERIM_PRAYER: "Interim protection as may be directed"
    },
    antiBail: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        place: "",
        fdate: "",
        district: "",
        counsel_address: "",
        counsel_code: "",
        verification: "",
        MAIN_PRAYER: "",
        INTERIM_PRAYER: ""
    },
    appealSuit: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        place: "",
        fdate: "",
        district: "",
        counsel_address: "",
        counsel_code: "",
        verification: "",
        MAIN_PRAYER: "",
        INTERIM_PRAYER: ""
    },
    bail: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        counsel_address: "",
        date_offence: "",
        place_offence: "",
        offence_section: "",
        date_remand: "",
        prev_crlmp_no: "",
        prev_court: "",
        prev_order_date: "",
        date_arrest: "",
        jail_name: "",
        place: "",
        fdate: "",
        verification: "",
        district: "",
        counsel_code: "",
        R25: "",
        MAIN_PRAYER: "",
        INTERIM_PRAYER: ""
    },
    ca: {
        highcourt: "",
        myear: "",
        OPNO: "",
        OPDATE: "",
        lowercourt: "",
        counsel_address: "",
        counsel_code: "",
        date_offence: "",
        place_offence: "",
        offence_section: "",
        date_remand: "",
        date_arrest: "",
        name_jail: "",
        verification: "",
        place: "",
        district: "",
        R25: "",
        MAIN_PRAYER: "",
        INTERIM_PRAYER: "",
        fdate: ""
    },
    caveat: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        caveat_no: "CAV/456/2025",
        myear: "2025",
        wp_no: "WP(C) 789/2025",
        OPNO: "CV/001/2025",
        lowercourt: "Original Side, Hyderabad",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        counsel_address: "No. 7, Counsel Chambers, Nampally, Hyderabad - 500001",
        interim_prayer: "For interim injunction",
        OPDATE: "2025-02-10",
        fdate: "2025-02-12",
        counsel_code: "HYD-007",
        district: "Hyderabad"
    },
    centralExciseAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        CEA_No: "CEA/2025/34",
        myear: "2025",
        order_in_original_no: "OIO/45/2024",
        order_in_appeal_no: "OIA/12/2025",
        final_order_no: "FO/78/2025",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        MAIN_PRAYER: "Allow the appeal and set aside the impugned order",
        INTERIM_PRAYER: "Stay recovery proceedings",
        fdate: "2025-01-20",
        district: "Hyderabad",
        counsel_code: "HYD-008",
        appeal_value: "₹5,00,000",
        court_fee: "₹5,000",
        stamp_duty: "₹200",
        batta_fee: "₹500",
        lowercourt: "Central Excise Commissionerate, Hyderabad",
        OPNO: "CE/09/2025",
        OPDATE: "2025-01-10"
    },
    cma: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        CMA_No: "CMA/321/2025",
        myear: "2025",
        lowercourt: "Family Court, Hyderabad",
        OPNO: "OP/876/2025",
        OPDATE: "2025-08-01",
        petitioner_name: "A. Rao",
        respondent_name: "B. Kumar",
        counsel_address: "Suite 4, Advocate Chambers, Hyderabad - 500032",
        counsel_code: "HYD-009",
        verification: "Verified and signed at Hyderabad",
        place: "Hyderabad",
        fdate: "2025-08-05",
        district: "Hyderabad",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Allow the CMA with costs",
        INTERIM_PRAYER: "Grant interim directions",
        court_fee: "₹2,000",
        stamp_duty: "₹100",
        batta_fee: "₹250",
        IA_details: "IA for interim relief dated 2025-08-02",
        running_index: ["1", "2"]
    },
    civilRevisionPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        lowercourt: "Civil Judge Court, Hyderabad",
        OPNO: "CRP/44/2025",
        OPDATE: "2025-07-18",
        myear: "2025",
        counsel_address: "Advocate Chambers, High Court, Nanakramguda, Hyderabad - 500032",
        counsel_code: "HYD-010",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        fdate: "2025-07-20",
        district: "Hyderabad",
        R25: "Applicable",
        MAIN_PRAYER: "For quashing the impugned order",
        INTERIM_PRAYER: "Stay the operation of impugned order",
        court_fee: "₹3,000",
        stamp_duty: "₹150",
        batta_fee: "₹300",
        IA_details: "IA for urgent hearing",
        running_index: ["1"],
        filing_numbers: { main: "CRP/44/2025" },
        full_cause_title: "A v. B",
        IA_PRAYER: "Grant urgent IA"
    },
    companyPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        lowercourt: "Company Bench, Hyderabad",
        CP_NO: "CP/11/2025",
        myear: "2025",
        counsel_address: "Company Law Chamber, High Court Campus, Hyderabad - 500032",
        counsel_code: "HYD-011",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        fdate: "2025-09-01",
        district: "Hyderabad",
        INTERIM_PRAYER: "Interim relief as may be appropriate",
        MAIN_PRAYER: "Petition for company winding up",
        court_fee: "₹7,500",
        registered_office: "No. 45, Banjara Hills, Hyderabad - 500034",
        auth_share_capital: "₹10,00,000",
        paidup_capital: "₹8,00,000",
        main_objects: ["Trading", "Manufacturing"],
        material_papers: "Memorandum and Articles, Balance Sheets",
        IA_details: "IA for appointment of provisional liquidator",
        judge_summons: "Summons to be issued",
        running_index: ["1", "2", "3"],
        filing_numbers: { cp: "CP/11/2025" },
        full_cause_title: "In the matter of XYZ Pvt. Ltd.",
        IA_PRAYER: "Appointment of provisional liquidator"
    },
    compromiseHc: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        ia_no: "IA/77/2025",
        crlp_no: "CRLP/21/2025",
        myear: "2025",
        lowercourt: "District Court, Hyderabad",
        OPNO: "OP/300/2025",
        OPDATE: "2025-10-05",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        fdate: "2025-10-10",
        district: "Hyderabad",
        counsel_code: "HYD-012",
        running_index: "1"
    },
    contemptCase: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        cc_no: "CC/12/2025",
        myear: "2025",
        OPNO: "OP/555/2025",
        OPDATE: "2025-06-30",
        lowercourt: "Original Side, Hyderabad",
        verification: "Verified in Hyderabad",
        place: "Hyderabad",
        fdate: "2025-07-02",
        district: "Hyderabad",
        counsel_code: "HYD-013",
        MAIN_PRAYER: "Punish for contempt and grant relief",
        INTERIM_PRAYER: "Immediate interim orders",
        running_index: "1"
    },
    counter: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        OPDATE: "2025-06-01",
        OPNO: "CTR/09/2025",
        verification: "Verified at Hyderabad",
        place: "Hyderabad",
        fdate: "2025-06-05",
        district: "Hyderabad",
        counsel_code: "HYD-014",
        INTERIM_PRAYER: "Interim relief prayed",
        DISTRICT: "Hyderabad"
    },
    criminalAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "CRL.A/88/2025",
        lowercourt: "Sessions Court, Hyderabad",
        myear: "2025",
        counsel_address: "Criminal Wing, Advocate Chambers, Hyderabad - 500032",
        OPDATE: "2025-04-28",
        MAIN_PRAYER: "Allow appeal and set aside conviction",
        place: "Hyderabad",
        fdate: "2025-05-02",
        counsel_code: "HYD-015",
        INTERIM_PRAYER: "Stay sentence pending appeal",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    criminalRevisionCase: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "CRR/33/2025",
        lowercourt: "Sessions Court, Hyderabad",
        myear: "2025",
        counsel_address: "Chamber No. 20, Counsel Complex, Hyderabad - 500032",
        OPDATE: "2025-04-15",
        MAIN_PRAYER: "Set aside order dated",
        place: "Hyderabad",
        fdate: "2025-04-18",
        counsel_code: "HYD-016",
        INTERIM_PRAYER: "Interim stay of order",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        DISTRICT: "Hyderabad",
        verification: "Verified in Hyderabad"
    },
    criminalRevisionCaseMacma: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "CRR-M/12/2025",
        lowercourt: "MACMA Bench, Hyderabad",
        myear: "2025",
        counsel_address: "MACMA Chambers, High Court Campus, Hyderabad - 500032",
        OPDATE: "2025-03-30",
        MAIN_PRAYER: "Revise impugned order",
        place: "Hyderabad",
        fdate: "2025-04-02",
        counsel_code: "HYD-017",
        INTERIM_PRAYER: "Stay execution",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    crossObjections: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "CO/45/2025",
        lowercourt: "Arbitration Tribunal, Hyderabad",
        myear: "2025",
        counsel_address: "Cross Objection Chambers, Hyderabad - 500032",
        OPDATE: "2025-02-25",
        MAIN_PRAYER: "Reject the claim and allow cross-objections",
        place: "Hyderabad",
        fdate: "2025-02-28",
        counsel_code: "HYD-018",
        INTERIM_PRAYER: "Interim protection till disposal",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    debtsRecoveryTribunal: {
        myear: "2025",
        counsel_address: "DRT Chambers, Hyderabad",
        MAIN_PRAYER: "Recovery of debt with costs",
        fdate: "2025-03-10",
        INTERIM_PRAYER: "Stay attachment",
        verification: "Verified at Hyderabad"
    },
    delayInRepresentation: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "DLR/05/2025",
        lowercourt: "District Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-06-10",
        place: "Hyderabad",
        fdate: "2025-06-12",
        counsel_code: "HYD-019",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    dispense: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "DSP/02/2025",
        lowercourt: "District Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-07-07",
        place: "Hyderabad",
        fdate: "2025-07-10",
        counsel_code: "HYD-020",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    expedite: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "EXP/14/2025",
        lowercourt: "Civil Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-08-12",
        place: "Hyderabad",
        fdate: "2025-08-15",
        counsel_code: "HYD-021",
        INTERIM_PRAYER: "For expedited hearing",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    extension: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "EXT/06/2025",
        lowercourt: "Family Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-09-01",
        place: "Hyderabad",
        fdate: "2025-09-05",
        counsel_code: "HYD-022",
        counsel_address: "No. 2, Counsel Chambers, Banjara Hills, Hyderabad - 500034",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad"
    },
    familyCourtsAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "FCA/09/2025",
        lowercourt: "Family Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-10-10",
        place: "Hyderabad",
        fdate: "2025-10-12",
        counsel_code: "HYD-023",
        counsel_address: "Chamber 9, Family Bench Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim custody order",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Allow appeal and modify order"
    },
    forbeing: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        lowercourt: "Civil Court, Hyderabad",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-11-01",
        counsel_code: "HYD-024",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim relief as may be necessary"
    },
    implead: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-11-05",
        counsel_code: "HYD-025",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim impleadment allowed",
        MAIN_PRAYER: "Allow impleadment as party"
    },
    incomeTaxAppellateTribunal: {
        highcourt: "Income Tax Appellate Tribunal, Hyderabad Bench",
        OPNO: "ITAT/07/2025",
        lowercourt: "Assessing Officer, Hyderabad",
        myear: "2025",
        OPDATE: "2025-02-14",
        place: "Hyderabad",
        fdate: "2025-02-20",
        counsel_code: "HYD-026",
        counsel_address: "Tax Chambers, High Court Campus, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Stay on demand",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Set aside assessment"
    },
    leave: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-01-10",
        counsel_code: "HYD-027",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Grant leave pending final disposal",
        MAIN_PRAYER: "Leave to appeal",
        OPNO: "LV/01/2025",
        OPDATE: "2025-01-05",
        lowercourt: "District Court, Hyderabad"
    },
    lrPetPet: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-02-01",
        counsel_code: "HYD-028",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim relief",
        MAIN_PRAYER: "Prayer as per petition",
        OPNO: "LRP/05/2025",
        OPDATE: "2025-01-28",
        lowercourt: "Lower Court, Hyderabad"
    },
    lrPreTreps: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-03-01",
        counsel_code: "HYD-029",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim orders sought",
        MAIN_PRAYER: "Main relief",
        OPNO: "LRT/02/2025",
        OPDATE: "2025-02-28",
        lowercourt: "Civil Judge, Hyderabad"
    },
    memoForProofOfService: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-04-10",
        DISTRICT: "Hyderabad"
    },
    civilMiscAppealMemorandum: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "CMA/123/2025",
        lowercourt: "District Court, Hyderabad",
        myear: 2025,
        OPDATE: "2025-07-15",
        counsel_address: "Suite 8, Advocate Chambers, High Court, Hyderabad - 500032",
        place: "Hyderabad",
        fdate: "2025-07-18",
        district: "Hyderabad",
        counsel_code: "HYD-046",
        verification: "Verified and signed at Hyderabad",
        INTERIM_PRAYER: "Grant interim relief pending disposal",
        MAIN_PRAYER: "Allow the civil miscellaneous appeal with costs",
        R25: "BCETG-2025-001"
    },
    transferCriminalPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "TCP/13/2025",
        lowercourt: "Sessions Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-06-20",
        place: "Hyderabad",
        fdate: "2025-06-22",
        counsel_code: "HYD-030",
        counsel_address: "Chamber 15, High Court Campus, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Transfer to a neutral court",
        MAIN_PRAYER: "Transfer petition allowed"
    },
    transferMiscPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "TMP/08/2025",
        lowercourt: "Civil Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-05-05",
        place: "Hyderabad",
        fdate: "2025-05-07",
        counsel_code: "HYD-031",
        counsel_address: "No. 21, Counsel Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim transfer",
        MAIN_PRAYER: "Transfer as prayed"
    },
    originalSideAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "OSA/66/2025",
        lowercourt: "Original Side, Hyderabad",
        myear: "2025",
        OPDATE: "2025-09-15",
        place: "Hyderabad",
        fdate: "2025-09-20",
        counsel_code: "HYD-032",
        counsel_address: "Original Side Chambers, High Court, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Stay on operation of decree",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Allow appeal on merits"
    },
    pil: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "PIL/03/2025",
        lowercourt: "N/A",
        myear: "2025",
        OPDATE: "2025-01-18",
        place: "Hyderabad",
        fdate: "2025-01-20",
        counsel_code: "HYD-033",
        counsel_address: "Public Interest Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Immediate remedial measures",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Relief in public interest"
    },
    quash: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "Q/44/2025",
        lowercourt: "Magistrate Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-02-04",
        place: "Hyderabad",
        fdate: "2025-02-06",
        counsel_code: "HYD-034",
        counsel_address: "Chamber No. 8, High Court Complex, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable"
    },
    receiveAndTransmit: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "RT/19/2025",
        lowercourt: "District Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-03-12",
        place: "Hyderabad",
        fdate: "2025-03-15",
        counsel_code: "HYD-035",
        counsel_address: "Transmission Chambers, High Court, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "For transmission of records",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Transmit record for hearing"
    },
    reviewPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "RVW/02/2025",
        lowercourt: "High Court Bench, Hyderabad",
        myear: "2025",
        OPDATE: "2025-04-05",
        place: "Hyderabad",
        fdate: "2025-04-07",
        counsel_code: "HYD-036",
        counsel_address: "Review Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Stay until review is heard"
    },
    secondAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "SA/77/2025",
        lowercourt: "District Court, Hyderabad",
        myear: "2025",
        OPDATE: "2025-06-25",
        place: "Hyderabad",
        fdate: "2025-06-28",
        counsel_code: "HYD-037",
        counsel_address: "Second Appeal Chambers, High Court, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim stay sought",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Admission and hearing on merits"
    },
    stateConsumerRedressalCommission: {
        highcourt: "State Consumer Disputes Redressal Commission, Hyderabad",
        OPNO: "SCRC/14/2025",
        lowercourt: "District Consumer Forum, Hyderabad",
        myear: "2025",
        OPDATE: "2025-08-20",
        place: "Hyderabad",
        fdate: "2025-08-22",
        counsel_code: "HYD-038",
        counsel_address: "Consumer Law Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim compensation",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Allow consumer claim"
    },
    taxAppellateTribunal: {
        highcourt: "Income Tax Appellate Tribunal, Hyderabad Bench",
        OPNO: "TAT/21/2025",
        lowercourt: "Assessing Officer, Hyderabad",
        myear: "2025",
        OPDATE: "2025-09-10",
        place: "Hyderabad",
        fdate: "2025-09-12",
        counsel_code: "HYD-039",
        counsel_address: "Tax Appeal Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Stay on recovery",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Set aside assessment"
    },
    vacate: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-10-01",
        counsel_code: "HYD-040",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Vacate interim order"
    },
    vacateMacma: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-10-05",
        counsel_code: "HYD-041",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Vacate MACMA order"
    },
    vakalath: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-01-02",
        counsel_code: "HYD-042",
        DISTRICT: "Hyderabad",
        verification: "Vakalatnama executed at Hyderabad",
        INTERIM_PRAYER: "N/A",
        counsel_address: "Vakalath Chambers, High Court, Hyderabad - 500032"
    },
    writIa: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        myear: "2025",
        place: "Hyderabad",
        fdate: "2025-02-14",
        counsel_code: "HYD-043",
        DISTRICT: "Hyderabad",
        INTERIM_PRAYER: "Interim directions as prayed"
    },
    writAppeal: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "WA/18/2025",
        lowercourt: "Original Side, Hyderabad",
        myear: "2025",
        OPDATE: "2025-03-08",
        place: "Hyderabad",
        fdate: "2025-03-10",
        counsel_code: "HYD-044",
        counsel_address: "Writ Appeal Chambers, High Court, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Stay on operation of order",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Allow writ appeal"
    },
    writPetition: {
        highcourt: "High Court of Judicature at Hyderabad for the States of Telangana and Andhra Pradesh",
        OPNO: "WP/99/2025",
        lowercourt: "N/A",
        myear: "2025",
        OPDATE: "2025-04-01",
        place: "Hyderabad",
        fdate: "2025-04-03",
        counsel_code: "HYD-045",
        counsel_address: "Writ Petition Chambers, Hyderabad - 500032",
        DISTRICT: "Hyderabad",
        verification: "Verified at Hyderabad",
        INTERIM_PRAYER: "Interim relief prayed",
        R23: "Applicable",
        R24: "Applicable",
        R25: "Applicable",
        MAIN_PRAYER: "Grant writ as prayed"
    }
};
