import { Document } from "docx";
import { combinedSections } from "../../../components/highcourt/combineSections";
import { h2UnderlineBoldCenter, h3BoldCenter, h3Center, h3Left, h3Right, h3underlineBoldCenter, h3UnderlineBoldLeft, h3UnderlineCenter, LineSpace, pageBreak, tabSpace } from "../../../components/templates/elementTypes";
import { writAppealSections } from "./waData";
import { createRightAlignPage } from "../../../components/templates/tableFunctions";
import { BetweenSection } from "../../../components/templates/BetweenSection";
import { create4LineFooter, SignatureFooter} from "../../../components/templates/FooterSections";
import { ChronologicalTable } from "../../../components/templates/ChronologicalTable";
import { OfficeUseTable } from "../../../components/templates/officeUseTable";
import { InfoTable } from "../../../components/templates/InfoTable";
import { ChallanTable } from "../../../components/templates/ChallanTable";
import { LowerCourtTable } from "../../../components/templates/LowerCourtTable";

export const WATemplate = (formData) => {
  return new Document({
    sections: [
      {
        properties: {},
        children: [
          ...combinedSections(writAppealSections("clause-15",formData),formData),
          pageBreak(),
          createRightAlignPage([
          h3Center(`${formData?.district || "«district»"} :: District`),
          h3Center("«highcourt»"),
          ...LineSpace(1),
          h3Center(`W.A.No.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          h3Center("AGAINST"),
          ...LineSpace(1),
          h3Center(`${formData?.OPNO || "«OPNO»"}`),
          ...LineSpace(1),
          ...BetweenSection(formData,"..Appellant","…Respondent"),
          ...LineSpace(15),
          h3underlineBoldCenter("G R O U N D S"),
          ...LineSpace(15),
          ...create4LineFooter([`Filed By:`,`M/s ${formData?.counsel_code || "«counsel_code»"}`,`Advocate`,`Counsel for Appellant`])
          ]),
          pageBreak(),
          ...combinedSections(writAppealSections("affidavit",formData),formData),
          h3Center(`ADVOCATE :: ${formData?.place || "«place»"}`),
          pageBreak(),
          h3UnderlineCenter("VERIFICATION STATEMENT"),
          h3Left(tabSpace(1)+`I, ${formData?.verification || "«verification»"}, being the petitioner/ person acquainted with the facts do hereby verify and state that the contents of the above paras of the Affidavit are true and correct to the best of my knowledge.  Hence verified at ${formData?.place || "«place»"} on this the day of ${formData?.fdate || "«fdate»"}`),
          h3Right(`Deponent`),
          pageBreak(),
          ...combinedSections(writAppealSections("sec-151-1st",formData),formData),
          pageBreak(),
          createRightAlignPage([
          h3Center(`${formData?.DISTRICT || "«DISTRICT»"} District`),
          ...LineSpace(1),
          h3Center(`${formData?.highcourt || "«highcourt»"}`),
          ...LineSpace(1),
          h3Center(`I.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          h3Center("IN"),
          h3Center(`W.A. No.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          ...LineSpace(15),
          h3underlineBoldCenter("DIRECTION PETITION"),
          ...LineSpace(15),
          ...create4LineFooter([`Filed By:`,`M/s ${formData?.counsel_code || "«counsel_code»"}`,`Advocate`,`Counsel for Petitioner`]),
        ]),
        pageBreak(),
         createRightAlignPage([
        h2UnderlineBoldCenter("HIGH COURT"),
        h3BoldCenter("WRIT APPEAL MISC.PETITION"),
        h3Center(`I.A.NO.${tabSpace(3)}OF «myear»`),
        h3Center("IN"),
        h3Center(`W.A.NO.${tabSpace(3)}OF «myear»`),
        ...LineSpace(1),
        h3Center(`${formData?.DISTRICT || "«DISTRICT»"}    District`),
        ...LineSpace(1),
        h3Left(``),
        h3Right(" ... Petitioner"),
        ...LineSpace(1),
        h3Left(`By ${formData?.counsel_code || "«counsel_code»"}`),
        h3Center("NATURE OF APPLICATION"),
        h3Center("(UNDER SEC. 151 C.P.C."),
        h3Left(`The Hon’ble Court may be pleased ${formData?.INTERIM_PRAYER || "«INTERIM_PRAYER»"} and pass such other order or orders may deem fit and proper in the circumstances of the case.`),
        ...LineSpace(3),
        h3Left(`PRESENTED ON: ${formData?.fdate || "«fdate»"}`),
        ...LineSpace(1),
        h3Left("REPRESENTED ON:"),
        ...LineSpace(1),
        h3Left(`By ${formData?.counsel_code || "«counsel_code»"}`),
      ]),
      pageBreak(),
      h3Center("MEMORANDUM OF WRIT APPEAL MISC. PETITION"),
      h3Center("(UNDER SEC. 151 OF CIVIL PROCEDURE CODE)"),
      ...combinedSections(writAppealSections("sec-151-2nd",formData),formData),
      pageBreak(),
       createRightAlignPage([
          h3Center(`${formData?.DISTRICT || "«DISTRICT»"} District`),
          ...LineSpace(1),
          h3Center(`${formData?.highcourt || "«highcourt»"}`),
          ...LineSpace(1),
          h3Center(`I.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          h3Center("IN"),
          h3Center(`W.A. No.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          ...LineSpace(15),
          h3underlineBoldCenter("LEAVE PETITION"),
          ...LineSpace(15),
          ...create4LineFooter([`Filed By:`,`M/s ${formData?.counsel_code || "«counsel_code»"}`,`Advocate`,`Counsel for Petitioner`]),
        ]),
        pageBreak(),
        createRightAlignPage([
        h2UnderlineBoldCenter("HIGH COURT"),
        h3BoldCenter("WRIT APPEAL MISC.PETITION"),
        h3Center(`I.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
        h3Center("IN"),
        h3Center(`W.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
        ...LineSpace(1),
        h3Center(`${formData?.DISTRICT || "«DISTRICT»"}    District`),
        ...LineSpace(1),
        h3Left(``),
        h3Right(" ... Petitioner"),
        ...LineSpace(1),
        h3Left(`By ${formData?.counsel_code || "«counsel_code»"}`),
        h3Center("NATURE OF APPLICATION"),
        h3Center("(UNDER SEC. 151 C.P.C."),
        h3Left(`The Hon’ble Court may be pleased to grant leave to the petitioner to file appeal against the order dated ${formData?.OPDATE || "«OPDATE»"} passed in ${formData?.OPNO || "«OPNO»"}, by the ${formData?.lowercourt || "«lowercourt»"} in the interest of justice and pass such other order or orders may deem fit and proper in the circumstances of the case.`),
        ...LineSpace(3),
        h3Left(`PRESENTED ON: ${formData?.fdate || "«fdate»"}`),
        ...LineSpace(1),
        h3Left("REPRESENTED ON:"),
        ...LineSpace(1),
        h3Left(`By${formData?.counsel_code || "«counsel_code»"}`),
      ]),
      pageBreak(),
       createRightAlignPage([
        h3BoldCenter(`${formData?.DISTRICT || "«DISTRICT»"} DISTRICT`),
        h2UnderlineBoldCenter("HIGH COURT"),
        h3BoldCenter("WRIT  APPEAL"),
        ...LineSpace(1),
        h3Center("(Under Clause 15 of Letters Patent)"),
        h3Center(`W.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
        h3Center("AGAINST"),
        h3Center(`${formData?.OPNO || "«OPNO»"}`),
        h3Center(`dated ${formData?.OPDATE || "«OPDATE»"}`),
        ...LineSpace(1),
        h3Left(``),
        h3Right("…Appellant/s"),
        ...LineSpace(1),
        h3Left(`By ${formData?.counsel_code || "«counsel_code»"}`),
        h3Center("Advocate"),
        ...LineSpace(1),
        h3Center("Vs"),
        ...LineSpace(1),
        h3Left(""),
        h3Left(`${formData?.RESPONDENT_NAME || "«RESPONDENT_NAME»"}`),
        h3Right("..Respondent/s"),
        h3Left(`Date of Order : ${formData?.OPDATE || "«OPDATE»"}`),
        h3Left("Appeal Presented on:"),
        h3Left("Re-presented on :"),
        h3Left("Filed:"),
        h3Left("Admitted:"),
        h3Left("Judge: The Hon’ble Mr.Justice"),
        h3Center(`${formData?.lowercourt || "«lowercourt»"}`),
        ...LineSpace(1),
        h3Left("To be heard on:"),
        h3Center(`I.A. No.${tabSpace(3)}of ${formData?.myear || "«myear»"}`)
      ]),
      pageBreak(),
      ChronologicalTable(formData),
      ...SignatureFooter([
    {
        left: [`DATE: ${formData?.fdate || "«fdate»"}`, `${formData?.place || "«place»"}`],
        right: ["", "Counsel for the Petitioner"]
    }
]),

      pageBreak(),
      h3underlineBoldCenter("BATA FORM"),
      ...LineSpace(1),
      h3Left(`${formData?.RESPONDENT_ADDRESS || "«RESPONDENT_ADDRESS»"}`),
      ...LineSpace(2),
     ...SignatureFooter([
    {
        left: [`DATE: ${formData?.fdate || "«fdate»"}`, `${formData?.place || "«place»"}`],
        right: ["", "Counsel for the Petitioner"]
    }
]),

      ...LineSpace(10),
      h3underlineBoldCenter("BATA FORM"),
      ...LineSpace(1),
      h3Left(`${formData?.RESPONDENT_ADDRESS || "«RESPONDENT_ADDRESS»"}`),
      ...LineSpace(2),
      ...SignatureFooter([
    {
        left: [`DATE: ${formData?.fdate || "«fdate»"}`, `${formData?.place || "«place»"}`],
        right: ["", "Counsel for the Petitioner"]
    }
]),

      pageBreak(),
      h3Center(`${formData?.highcourt || "«highcourt»"}`),
      ...LineSpace(1),
      h3Center(`W.A.NO.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
      ...BetweenSection(formData,"..Petitioner","..Respondent"),
      ...LineSpace(1),
      h3underlineBoldCenter("COURT FEE"),
      ...LineSpace(10),
     ...SignatureFooter([
    {
        left: [`DATE: ${formData?.fdate || "«fdate»"}`, `${formData?.place || "«place»"}`],
        right: ["", "Counsel for the Petitioner"]
    }
]),
      pageBreak(),
      h3UnderlineCenter("MEMO OF APPEARANCE"),
      ...combinedSections(writAppealSections("memo-of-appearance",formData),formData),
      pageBreak(),
      createRightAlignPage([
          h3Center(`${formData?.DISTRICT || "«DISTRICT»"} District`),
          ...LineSpace(1),
          h3Center(`${formData?.highcourt || "«highcourt»"}`),
          ...LineSpace(1),
          h3Center(`W.A. No.${tabSpace(3)}OF ${formData?.myear || "«myear»"}`),
          h3Center("IN"),
          h3Center(`${formData?.OPNO || "«OPNO»"}`),
          ...LineSpace(15),
          h3underlineBoldCenter("MEMO OF APPEARANCE"),
          ...LineSpace(15),
          ...create4LineFooter([`Filed By:`,`M/s ${formData?.counsel_code || "«counsel_code»"}`,`Advocate`,`Counsel for Petitioner`]),
        ]),
        pageBreak(),
        ...OfficeUseTable(formData),
        ...InfoTable(formData),
        ...ChallanTable(formData),
        ...LowerCourtTable(formData),
        pageBreak(),
        h3UnderlineBoldLeft("Full Cause Title:"),
        ...BetweenSection(formData,"..Petitioner(s)","..Respondent(s)"),
        pageBreak(),
        h3UnderlineBoldLeft("Main Case Prayer :"),
        ...LineSpace(1),
        h3Left(tabSpace(1)+`It is therefore prayed that this Hon'ble Court may be pleased ${formData?.MAIN_PRAYER || "«MAIN_PRAYER»"} and pass such other order or orders may deem fit and proper in the circumstances of the case.`),
        ...LineSpace(2),
         h3UnderlineBoldLeft("IA(s) Prayer:"),
        ...LineSpace(1),
        h3Left(tabSpace(1)+`It is also just and necessary that this Hon'ble Court may be pleased ${formData?.INTERIM_PRAYER || "«INTERIM_PRAYER»"} pending disposal of the above writ petition and pass such other order or orders may deem fit and proper in the circumstances of the case.`),
        ...LineSpace(2),
        h3Left(tabSpace(1)+`It is also just and necessary that this Hon'ble Court may be pleased to grant leave to the petitioner to file appeal against the order dated ${formData?.OPDATE || "«OPDATE»"} passed in ${formData?.OPNO || "«OPNO»"}, by the ${formData?.lowercourt || "«lowercourt»"} in the interest of justice and pass such other order or orders may deem fit and proper in the circumstances of the case.`),
    ],
      },
    ],
  });
};
